i-am-alive:
  path: /api/comment/i-am-alive
  controller: App\IAmAlive\Infrastructure\IAmAliveController::index

comment:
  path: /api/comment/comment/{commentId}
  controller: App\Comment\Infrastructure\CommentEndpoint::getCommentAsJson

post-comment:
  path: /api/comment/comment
  controller: App\Comment\Infrastructure\CommentPostEndpoint::sendCommentToEventBus
  methods: POST